backend:
  name: git-gateway

media_folder: "static/images"
public_folder: "/images"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "homepage"
        file: "content/homepage.json"
        extension: "json"
        description: "Home Page Content"
        fields:
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - {
              label: "Value Prop Title",
              name: "value_prop_title",
              widget: "string",
            }
          - {
              label: "Value Prop Paragraph",
              name: "value_prop_paragraph",
              widget: "text",
            }
          - label: "Enhancements & Add-ons"
            name: "add_ons"
            widget: "list"
            fields:
              - { label: "Add-on Title", name: "title", widget: "string" }
              - {
                  label: "Add-on Description",
                  name: "description",
                  widget: "text",
                }
          - label: "Reviews"
            name: "reviews"
            widget: "list"
            fields:
              - { label: "Review Text", name: "text", widget: "text" }
              - { label: "Review Author", name: "author", widget: "string" }
              - { label: "Review Link URL", name: "link", widget: "string" }
              - { label: "Review Source", name: "source", widget: "string" }
          - {
              label: "Gift Certificate Title",
              name: "gift_cert_title",
              widget: "string",
            }
          - {
              label: "Gift Certificate Paragraph",
              name: "gift_cert_paragraph",
              widget: "text",
              required: false,
            }
          - {
              label: "Gift Certificate Link",
              name: "gift_cert_link",
              widget: "string",
            }

      - label: "Services Page"
        name: "servicespage"
        file: "content/servicespage.json"
        extension: "json"
        description: "Serives Page Content"
        fields:
          - label: "Pricing Options"
            name: "prices"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }
          - label: "Pricing Notes"
            name: "pricingNotes"
            widget: "list"
            fields:
              - { label: "Description", name: "description", widget: "text" }
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }
      - label: "About Page"
        name: "aboutpage"
        file: "content/aboutpage.json"
        extension: "json"
        description: "About Page Content"
        fields:
          - {
              label: "About Us Copy",
              name: "aboutCopy",
              widget: "text",
              hint: "Make sure to include a (<br/>) between line breaks",
            }
          - {
              label: "License Link Text",
              name: "licenseLinkText",
              widget: "string",
            }
          - {
              label: "URL to License",
              name: "licenseLinkAddress",
              widget: "string",
            }
          - label: "Team Members"
            name: "team"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Portrait", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }
          - label: "Hours"
            name: "hours"
            widget: "list"
            fields:
              - { label: "Day", name: "day", widget: "string" }
              - { label: "Hours", name: "hours", widget: "string" }
      - label: "Book Now Page"
        name: "booknowpage"
        file: "content/booknowpage.json"
        extension: "json"
        description: "Book Now Page Content"
        fields:
          - label: "Promo Codes"
            name: "promoCodes"
            widget: "list"
            fields:
              - { label: "Promo Code", name: "code", widget: "string" }
              - { label: "Promo URL", name: "url", widget: "string" }
  - label: "General Content"
    name: "globalContent"
    files:
      - label: "Footer Content"
        name: "footerContent"
        file: "content/footercontent.json"
        extension: "json"
        description: "Site footer conent"
        fields:
          - { label: "Address Line 1", name: "address1", widget: "string" }
          - { label: "Address Line 2", name: "address2", widget: "string" }
          - { label: "Address Line 3", name: "address3", widget: "string" }
          - { label: "Phone Number", name: "phoneNumber", widget: "string" }
          - {
              label: "Facebook Link",
              name: "facebookAddress",
              widget: "string",
              required: false,
              hint: "The icon will not appear, if the field is left blank",
            }
          - {
              label: "Instagram Link",
              name: "instagramAddress",
              widget: "string",
              required: false,
              hint: "The icon will not appear, if the field is left blank",
            }
          - {
              label: "Twitter Link",
              name: "twitterAddress",
              widget: "string",
              required: false,
              hint: "The icon will not appear, if the field is left blank",
            }
          - {
              label: "YouTube Link",
              name: "youtubeAddress",
              widget: "string",
              required: false,
              hint: "The icon will not appear, if the field is left blank",
            }
